### PR TITLE
Added box art, titles and snaps; consolidated old request.

### PR DESCRIPTION
**Pull request by ghost**
I can still remove the old No-intro titled files if need be that are currently in the library.

### CODE REVIEW

**Comment by MarcoEstevez** [comment]
Nice work @masanasake

I did not get your question, what do you mean by _"remove the old No-intro titled"_

**Comment by ghost** [comment]
So I had added some of these under the No-intro names. When you scan the files, it shows the bulk of them as just (USA) for the most part, no (Rev 1) or infinitely many languages behind them. The files I'm uploading cater to what they actually scan as. Pretty sure these No-intro named ones can just be deleted since they were made in error. You can see where I messed this up: 
image
The underscore is correct because they scan with a colon.

**Comment by RobLoach** [comment]
Fiels that no longer match the names are likely because No-Intro renamed the entry. They are listed as orphans in:
https://github.com/RobLoach/libretro-thumbnails-check/blob/master/out/Nintendo%20-%20Wii%20Orphans.txt

Just needs to be checked and renamed to match the new name most of the time. Here's the full report:
https://raw.githubusercontent.com/RobLoach/libretro-thumbnails-check/master/out/Nintendo%20-%20Wii.txt

Also, Wii is likely Redump, or GameTDB.

**Comment by ghost** [comment]
None of these are on that list of orphans; these files/names are correct when scanned by Retroarch. I can add everything I've uploaded for wii thus far with the No-intro names as well if you're fine with having basically double entries. Not sure where you stand on that

**Comment by ghost** [comment]
image
image
Example: both of these exist on the list of missing files. You're fine with both, even if they're the same images?

**Comment by RobLoach** [comment]
Redump uses ` - `, while GameTDB uses `: `.

https://www.gametdb.com/Wii/RDKE01

We can have both, and not increase file size, by using symlinks. I'll send you a Pull Request.

**Comment by ghost** [comment]
Okay, so the current libretro-thumbnails:master is basically 100% GameTDB naming conventions, minus the couple that I had messed up with the last pull request that used the Redump names. This request removes the incorrect Redump named files and replaces them with GameTDB named files so that libretro-thumbnails:master is again 100% TDB. Would you mind reviewing and merging this just to move past the confusion. Seems like regardless of what happens with the symbolic links, this change will need to occur so all the files are in line.

**Review by RobLoach — APPROVED** [review]

**Comment by MarcoEstevez** [comment]
LGTM

**Pull request merged**
