### PR TITLE
Added Metroid Prime 3

### PR DESCRIPTION
**Pull request by gerad-not-edgar**

### CODE REVIEW

**Comment by RobLoach** [comment]
Thanks so much!

**Review by RobLoach — APPROVED** [review]

**Comment by gerad-not-edgar** [comment]
Thanks for the merge @RobLoach ; any update on what's going on with DS? It's still not working.

**Comment by RobLoach** [comment]
What's going on with DS?

**Comment by gerad-not-edgar** [comment]
I haven't been able to download thumbnails for it for a month or two now. I tried it this morning and it still doesn't work for some reason.

**Pull request merged**
