### PR TITLE
Nintendo_-_Wii

### PR DESCRIPTION
**Pull request by zach-morris**

### CODE REVIEW

**Comment by MarcoEstevez** [comment]
LGTM

**Comment by zach-morris** [comment]
Yeah, this one i even had trouble pushing since it was so big.  Hopefully it merges cleanly

**Comment by MarcoEstevez** [comment]
I´m willing to merge it, what do you say @RobLoach?

**Comment by RobLoach** [comment]
The largest merge in GitHub history. The GitHub UI can't even render it lol. I had to check it out locally.

**Pull request merged**
